#!/usr/bin/env bash
# installs nginx and configure

sudo apt update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.htmli
